### ISSUE TITLE
Download the code

### ISSUE THREAD

**Issue by BramWerbrouck** [markroland/sand-table-pattern-maker#27]
How can I change the download button so that when a pattern is made, it will save the Gcode or thetaRho to the specified path, and not in my standard download folder.

for example: I add a new folder "WORKING PATHS" and every time you make something and hit the download button, it saves the code (maybe with an extra field "NAME") in the folder "working paths"?

**Comment by markroland** [comment]
Hi @BramWerbrouck . I'm pretty sure that this would have to be a browser-based setting. I'm not aware of Javascript being able to direct the location of saved files. Here is a SO link that may provide useful: https://stackoverflow.com/questions/34870711/download-a-file-at-different-location-using-html5
